web/router.ex
defmodule HelloPhoenix.Router do
  use HelloPhoenix.Web, :router

@doc """
Routes requests to the coresponding contorller and action
"""

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end


  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HelloPhoenix do
    pipe_through [:browser, :with_session] # Use the default browser stack

    get "/", PageController, :index
    get "/test", PageController, :test
    resources "/comments", CommentController
    resources "/posts", PostController
    resources "/user", UserAuthController
    get "/register", UserAuthController, :index
    get "/login", UserAuthController, :login
    post "/login", UserAuthController, :validate
    get "/current", UserAuthController, :current_user_state
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/transactions", TransactionController
  end


pipeline :with_session do
  plug Guardian.Plug.VerifySession
  plug Guardian.Plug.LoadResource
  plug HelloPhoenix.CurrentUser
end

  # Other scopes may use custom stacks.
  # scope "/api", HelloPhoenix do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule HelloPhoenix.LayoutView do
  use HelloPhoenix.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello HelloPhoenix!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">

            <%= if @current_user do %>
            <li><%= @current_user.username %> (<%= @current_user.id %>)</li>
            <li><%= link "View worth", to: user_auth_path(@conn, :current_user_state) %></li>
            <li>
              <%= link "Sign out", to: session_path(@conn, :delete,
                                                    @current_user),
                                   method: "delete" %>
            </li>
            <li>
              <%= link "Transactions", to: transaction_path(@conn, :index) %>
            </li>
          <% else %>
          <li>
            <%= link "Register", to: "/register" %>
          </li>
          <li>
            <%= link "Sign in", to: session_path(@conn, :new) %>
          </li>
          <% end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :auth) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>